numero1 = float(input('Digite o primeiro numero a ser calculado: '));
numero2 = float(input('Digite o segundo numero a ser calculado: '));
soma =numero1 + numero2;
sub = numero1 - numero2;
mult = numero1 * numero2;
div = numero1 / numero2;
print('a soma dos numeros é',soma);
print('a subtraçao dos numeros é',sub);
print('a multiplicaçao dos numeros é',mult);
print('a divisao dos numeros é',div);
